### ISSUE TITLE
User auth review 

### ISSUE THREAD

**Issue by ken-zhong** [ken-zhong/pxl-On#24]
Auth component finished for now (need to complete next step before I can finish the last styling bits).

**Comment by AM-Harris** [comment]
- [ ]   When I try to log out, I get this error: "Uncaught Error: Given action "RECEIVE_ERRORS", reducer "session" returned undefined. To ignore an action, you must explicitly return the previous state. If you want this reducer to hold no value, you can return null instead of undefined." I was logged in looking at it before, so I can't log out to test logging in again

**Comment by ken-zhong** [comment]
Hi Ali, where exactly are you seeing this error? I couldn't replicate it on my side, but I did go into my sessions reducer and saw that I didn't have a case RECEIVE_ERRORS, but the default case returns the previous state. Wouldn't that have caught that? I also realized I forgot to comment out another unfinished reducer before I pushed, so I fixed that as well.

**Comment by AM-Harris** [comment]
In the console. I hover over dropdown, click log out, and nothing happens. When I check the console, the above error is there. Are you sure heroku is up to date and you are testing in heroku, not just locally?

**Comment by ken-zhong** [comment]
Hi Ali, the Heroku version seems to be working correctly on my end. I pushed to Heroku again with an explicit return state anyways.
Now that I think about it, I'm not handling the case where you click logout and you're not currently logged in. Is that what happened?

**Comment by AM-Harris** [comment]
Potentially. I have no way to navigate to login or signup from /home so it appears I am logged in. Also, I shouldn't be able to see a logout button unless I am logged in. I am pretty sure I am logged in though, because when I try to navigate directly to /login, I get redirected to /home

**Comment by AM-Harris** [comment]
See if you can figure that one out. I think reseeding will work.  The only other thing you need is a demo login button to log in as a demo user. This is so someone can easily browse your site functionality in a logged in state without having to fill out any forms. Thanks!

**Comment by ken-zhong** [comment]
Hi, I added a demo user and fixed a bug related to the login, and I reset the database on heroku. It should work now!

**Comment by AM-Harris** [comment]
Looks good to me!
